"""initial schema: corpus, events, postings, sources

Revision ID: 2c9e1cb3f76f
Revises: 
Create Date: 2026-07-24 02:12:37.427066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c9e1cb3f76f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('ats_vendor', sa.String(length=40), nullable=True),
    sa.Column('ats_slug', sa.Text(), nullable=True),
    sa.Column('careers_url', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_ats', 'companies', ['ats_vendor', 'ats_slug'], unique=False)
    op.create_index(op.f('ix_companies_canonical_name'), 'companies', ['canonical_name'], unique=True)
    op.create_table('corpus_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fact_type IN ('project','experience','skill','achievement','education')", name='ck_fact_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_facts_user_id'), 'corpus_facts', ['user_id'], unique=False)
    op.create_table('corpus_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('situation', sa.Text(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('source_fact_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('competency_tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_stories_user_id'), 'corpus_stories', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_entity', 'events', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_events_entity_id'), 'events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('practice_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('problem_slug', sa.Text(), nullable=False),
    sa.Column('pattern_tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('time_taken_sec', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("outcome IN ('solved_clean','solved_with_hint','solved_over_time','failed')", name='ck_attempt_outcome'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_attempts_attempted_at'), 'practice_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_practice_attempts_user_id'), 'practice_attempts', ['user_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_user_id'), 'resume_versions', ['user_id'], unique=False)
    op.create_table('source_health',
    sa.Column('source_id', sa.String(length=60), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_row_count', sa.Integer(), nullable=True),
    sa.Column('previous_row_count', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_quarantined', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('ats_job_id', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_available', sa.Boolean(), nullable=False),
    sa.Column('season', sa.Enum('SPRING', 'SUMMER', 'FALL', 'WINTER', name='season'), nullable=True),
    sa.Column('term_year', sa.Integer(), nullable=True),
    sa.Column('term_rule', sa.String(length=40), nullable=False),
    sa.Column('term_evidence', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.Enum('INTERNSHIP', 'NEW_GRAD', 'OTHER', name='employment_type'), nullable=False),
    sa.Column('role_family', sa.Enum('SWE', 'AI_ML', 'DATA', 'HARDWARE', 'QUANT', 'PRODUCT', 'SECURITY', 'OTHER', name='role_family'), nullable=False),
    sa.Column('sponsorship', sa.Enum('UNKNOWN', 'OFFERS', 'DOES_NOT_OFFER', 'CITIZENSHIP_REQUIRED', name='sponsorship'), nullable=False),
    sa.Column('locations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location_labels', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_postings_active_posted', 'postings', ['is_active', 'posted_at'], unique=False)
    op.create_index(op.f('ix_postings_ats_job_id'), 'postings', ['ats_job_id'], unique=False)
    op.create_index(op.f('ix_postings_canonical_url'), 'postings', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_postings_company_id'), 'postings', ['company_id'], unique=False)
    op.create_index(op.f('ix_postings_is_active'), 'postings', ['is_active'], unique=False)
    op.create_index(op.f('ix_postings_normalized_title'), 'postings', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_postings_posted_at'), 'postings', ['posted_at'], unique=False)
    op.create_index('ix_postings_term', 'postings', ['season', 'term_year'], unique=False)
    op.create_table('reported_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('problem_slug', sa.Text(), nullable=True),
    sa.Column('pattern_tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('reported_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reported_questions_company_id'), 'reported_questions', ['company_id'], unique=False)
    op.create_index(op.f('ix_reported_questions_reported_date'), 'reported_questions', ['reported_date'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('resume_version_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'posting_id', name='uq_application_posting')
    )
    op.create_index(op.f('ix_applications_posting_id'), 'applications', ['posting_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('posting_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_fingerprint', name='uq_source_fingerprint')
    )
    op.create_index(op.f('ix_posting_sources_posting_id'), 'posting_sources', ['posting_id'], unique=False)
    op.create_index(op.f('ix_posting_sources_source_id'), 'posting_sources', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posting_sources_source_id'), table_name='posting_sources')
    op.drop_index(op.f('ix_posting_sources_posting_id'), table_name='posting_sources')
    op.drop_table('posting_sources')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_posting_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_reported_questions_reported_date'), table_name='reported_questions')
    op.drop_index(op.f('ix_reported_questions_company_id'), table_name='reported_questions')
    op.drop_table('reported_questions')
    op.drop_index('ix_postings_term', table_name='postings')
    op.drop_index(op.f('ix_postings_posted_at'), table_name='postings')
    op.drop_index(op.f('ix_postings_normalized_title'), table_name='postings')
    op.drop_index(op.f('ix_postings_is_active'), table_name='postings')
    op.drop_index(op.f('ix_postings_company_id'), table_name='postings')
    op.drop_index(op.f('ix_postings_canonical_url'), table_name='postings')
    op.drop_index(op.f('ix_postings_ats_job_id'), table_name='postings')
    op.drop_index('ix_postings_active_posted', table_name='postings')
    op.drop_table('postings')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_resume_versions_user_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_practice_attempts_user_id'), table_name='practice_attempts')
    op.drop_index(op.f('ix_practice_attempts_attempted_at'), table_name='practice_attempts')
    op.drop_table('practice_attempts')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_entity_id'), table_name='events')
    op.drop_index('ix_events_entity', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_corpus_stories_user_id'), table_name='corpus_stories')
    op.drop_table('corpus_stories')
    op.drop_index(op.f('ix_corpus_facts_user_id'), table_name='corpus_facts')
    op.drop_table('corpus_facts')
    op.drop_index(op.f('ix_companies_canonical_name'), table_name='companies')
    op.drop_index('ix_companies_ats', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
